apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vka1b6wzq-python 
  janus-idp.io/tekton: vka1b6wzq-python
  backstage.io/kubernetes-id: vka1b6wzq-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vka1b6wzq-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml