apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: vka1b6wzq-python-gitops
  description: This is GitOps manifest for vka1b6wzq-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=vka1b6wzq-python
    backstage.io/kubernetes-id: vka1b6wzq-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: vka1b6wzq-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:vka1b6wzq-python
